import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Quiz from '../components/Quiz'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Programming Languages Quiz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Quiz />
      </main>

      <footer>footer</footer>
    </>
  )
}

export default Home
